# Generated by Django 4.1.5 on 2023-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
