# Generated by Django 4.1.5 on 2023-01-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mimage', to='games.image'),
            preserve_default=False,
        ),
    ]
