# Generated by Django 4.1.5 on 2023-01-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_mimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(related_name='images', to='games.image'),
        ),
    ]
