# Generated by Django 4.1.5 on 2023-01-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(to='games.image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
