# Generated by Django 4.1.5 on 2023-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_images_alter_game_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='images',
        ),
    ]
