# Generated by Django 4.1.5 on 2023-01-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_game_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mimage',
        ),
        migrations.AddField(
            model_name='image',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
    ]
