# Generated by Django 4.1.5 on 2023-01-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_game_mimage_image_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mimage',
            field=models.URLField(default='google.com', max_length=255),
            preserve_default=False,
        ),
    ]
