# Generated by Django 4.1.5 on 2023-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
